language: node_js
node_js:
- lts/*
dist: trusty
sudo: false
addons:
  ssh_known_hosts:
  - $IP
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
- provider: script
  script: ".travis/deploy.sh"
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_6b0e97a6d9b1_key -iv $encrypted_6b0e97a6d9b1_iv
  -in .travis/deploy.enc -out .travis/deploy -d